name: mobilis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  flutter_map: ^6.1.0     
  latlong2: 0.9.1      
  file_picker: ^6.1.1    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mobilis-logo.png
    - assets/images/mini_map.png
    - assets/images/zoning.png
    - assets/images/gps_map.png
